language: python
python:
  - "3.7"
language: node_js
node_js:
  - "node"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/lux-org/lux-widget
script:
  - echo "successful build" 